# Generated by Django 4.2.6 on 2023-10-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0007_likedpost_post_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked',
            new_name='likes',
        ),
    ]
