# Generated by Django 4.2.6 on 2023-10-18 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts_app', '0008_rename_liked_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts_app.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='likes',
            field=models.ManyToManyField(related_name='likednotes', through='posts_app.LikedNote', to=settings.AUTH_USER_MODEL),
        ),
    ]
