# Generated by Django 4.2.6 on 2023-10-22 14:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts_app', '0012_rename_reply_postcommentreply'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='PostComment',
        ),
    ]
