# Generated by Django 4.2.6 on 2023-10-22 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts_app', '0014_likedpostcommentreply_likedpostcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='likes',
            field=models.ManyToManyField(related_name='likedpostcomments', through='posts_app.LikedPostComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcommentreply',
            name='likes',
            field=models.ManyToManyField(related_name='likedpostcommentsreplies', through='posts_app.LikedPostCommentReply', to=settings.AUTH_USER_MODEL),
        ),
    ]
