# Generated by Django 4.2.6 on 2023-10-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0016_remove_post_artist_alter_post_image_alter_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
