# Generated by Django 4.2.6 on 2023-10-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0017_remove_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
