# Generated by Django 4.2.6 on 2023-10-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0018_alter_post_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='image',
        ),
    ]
