# Generated by Django 4.2.6 on 2023-11-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0021_rename_tag_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
