# Generated by Django 4.2.7 on 2023-11-28 17:24

from django.db import migrations, models
import posts_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0027_alter_post_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='user-uploads', validators=[posts_app.validators.file_size]),
        ),
    ]
