# Generated by Django 4.2.7 on 2023-12-11 10:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0029_repost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repost',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
