# Generated by Django 4.2.7 on 2023-12-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0030_alter_repost_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repost',
            options={'ordering': ['-date_reposted']},
        ),
    ]
