# Generated by Django 4.2.7 on 2023-11-21 11:45

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='static/images/default.png', force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[600, 600], upload_to='profilepics/'),
        ),
    ]
