# Generated by Django 4.2.7 on 2023-12-09 15:23

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0008_profile_profilebackground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilebackground',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='static/images/profile_bg.jpg', force_format=None, keep_meta=True, null=True, quality=70, scale=None, size=[1920, 1080], upload_to='profilepics/'),
        ),
    ]
